version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: xcodebuild -project Demo.xcodeproj -scheme "Tests" -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' test | xcpretty

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
